services:
  express-app:
    image: xiaosihuangsi/express-app
    ports:
      - 3000:8080
  watchtower:
    image: nickfedor/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
